#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/mach/mt6580/k80hd/dct/dct/\
  							 -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6580/include/mach/\
							 -I$(srctree)/drivers/misc/mediatek/include/mt-plat/

obj-y				+= leds_strobe.o
