#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9806e_wvga_dsi_vdo_TXD_pixi44.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc/\
				             -I$(srctree)/drivers/misc/mediatek/include/mt-plat/\
				             -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6580/include/mach/




